Add CI configuration to run tests and linter
0xPolygon/staking-contracts pull request #11
Opened 2022-02-02 12:45 UTC by PtitLuca

# Description

This PR adds the configuration for the GA to run the Smart Contract tests and the linter - solhint.
It also looks for common vuln. in the solidity code.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2022-02-08 08:32 UTC, Kourin1996 reviewed
Looks good. But I think it's better to show solint result in PR as a comment

2022-02-08 08:32 UTC, Kourin1996 commented on .github/workflows/main.yml
> +        run: solhint 'contracts/Staking.sol'
Can you define this script in package.json so that we can call `npm run lint` here

2022-02-10 09:01 UTC, Kourin1996 requested changes

2022-02-10 09:01 UTC, Kourin1996 commented on package.json
> +    "lint": "solhint 'contracts/Staking.sol'"
I suppose you can use wildcard instead of specifying the file

2022-02-15 09:22 UTC, Kourin1996 approved these changes

2022-03-02 09:43 UTC, lazartravica approved these changes

2022-03-02 09:43 UTC, merged